name: ${pluginName}
version: ${pluginVersion}
main: io.github.irishgreencitrus.sourgraves.SourGraves
description: A better graves plugin
author: irishgreencitrus
api-version: ${minecraftVersion}
commands:
  sourgraves:
    description: Manage the SourGraves plugin
    usage: "Usage: /sourgraves <subcommand>"
permissions:
  sourgraves.admin.server:
    description: Allows you to use `/sourgraves disk` and `/sourgraves config`
    default: op
  sourgraves.admin.settings:
    description: Allows you to use `/sourgraves settings`
    default: op
  sourgraves.admin.give:
    description: Allows you use `/sourgraves give`
    default: op
  sourgraves.player.graveaccess:
    description: A player with this permission can open any grave, regardless of whether it is public.
    default: false
  sourgraves.player.permagraves:
    description: A player with this permission will have a grave that never expires.
    default: false
  sourgraves.utils.player:
    description: Allows you to use `/sourgraves player`
    default: op
  sourgraves.utils.locateown:
    description: Allows you to use `/sourgraves locate`
    default: true